### ISSUE TITLE
Week 2: Using Objects

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#4]
**Crossover Grade: 2.7+/3  Graded by: Samaya**
**Teacher Grade: 2.8/3**
[Team Menu](https://sarayu-pr11.github.io/teamGrapeSnails/jupyter/2022/09/05/menu.html)
[Team Repo](https://github.com/sarayu-pr11/teamGrapeSnails)
[Team Planning of Objects](https://sarayu-pr11.github.io/teamGrapeSnails/markdown/2022/09/01/features.html)
[Code.org Key Takeaways](https://sarayu-pr11.github.io/sarayucsa/2022/09/05/codeorg.html)

**Comment by samayasankuratri** [comment]
## **Score: 2.7+/3**
 **Reviewed by Samaya Sankuratri**

Team Menu - Has done all the features assigned and added them to team menu. Did 3 features instead of 1. 
Team Repo - Contributed to it
Team Planning of Objects - Marked off all features completed and kept up with assignments.
Code.org Key Takeaways - Completed all 15 units in unit 1 and answered all the hack questions.
